# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cnc_mill_pb2 as cnc__mill__pb2


class CNCMillStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GoTo = channel.unary_unary(
        '/CNCMill/GoTo',
        request_serializer=cnc__mill__pb2.Position.SerializeToString,
        response_deserializer=cnc__mill__pb2.Response.FromString,
        )


class CNCMillServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GoTo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CNCMillServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GoTo': grpc.unary_unary_rpc_method_handler(
          servicer.GoTo,
          request_deserializer=cnc__mill__pb2.Position.FromString,
          response_serializer=cnc__mill__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CNCMill', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
